using Microsoft.Data.SqlClient;
using TAPortal.Web.Models;
namespace TAPortal.Web.Services;
public sealed class OperationalDb(IConfiguration config)
{
 private SqlConnection Open()=>new(config.GetConnectionString("DefaultConnection") ?? throw new InvalidOperationException("Missing DefaultConnection."));
 public async Task<List<PartnerListRow>> Partners(){var a=new List<PartnerListRow>();await using var c=Open();await c.OpenAsync();await using var q=new SqlCommand("SELECT Id,Code,Name,PartnerType,TaxCode,Status,IsPlatformOwner FROM dbo.Partners WHERE IsDeleted=0 ORDER BY IsPlatformOwner DESC,Name",c);await using var r=await q.ExecuteReaderAsync();while(await r.ReadAsync())a.Add(new(r.GetGuid(0),r.GetString(1),r.GetString(2),r.GetString(3),r.IsDBNull(4)?null:r.GetString(4),r.GetString(5),r.GetBoolean(6)));return a;}
 public async Task<List<BankAccountListRow>> BankAccounts(){var a=new List<BankAccountListRow>();await using var c=Open();await c.OpenAsync();await using var q=new SqlCommand("SELECT Id,BankCode,AccountNumber,AccountHolderName,BankApiConnected,Status FROM dbo.PartnerBankAccounts ORDER BY CreatedAt DESC",c);await using var r=await q.ExecuteReaderAsync();while(await r.ReadAsync())a.Add(new(r.GetGuid(0),r.GetString(1),r.GetString(2),r.IsDBNull(3)?null:r.GetString(3),r.GetBoolean(4),r.GetString(5)));return a;}
 public async Task<List<BankTransactionListRow>> Transactions(){var a=new List<BankTransactionListRow>();await using var c=Open();await c.OpenAsync();await using var q=new SqlCommand("SELECT TOP 500 t.Id,t.TransactionDate,t.Direction,t.Amount,t.PaymentCode,t.Content,a.AccountNumber FROM dbo.BankTransactions t JOIN dbo.PartnerBankAccounts a ON a.Id=t.BankAccountId ORDER BY t.TransactionDate DESC",c);await using var r=await q.ExecuteReaderAsync();while(await r.ReadAsync())a.Add(new(r.GetGuid(0),r.GetDateTime(1),r.GetString(2),r.GetDecimal(3),r.IsDBNull(4)?null:r.GetString(4),r.IsDBNull(5)?null:r.GetString(5),r.GetString(6)));return a;}
 public async Task<List<PaymentRequestListRow>> Payments(){var a=new List<PaymentRequestListRow>();await using var c=Open();await c.OpenAsync();await using var q=new SqlCommand("SELECT p.Id,p.Code,p.PaymentCode,p.AmountDue,p.AmountPaid,p.Status,c.Name FROM dbo.PaymentRequests p LEFT JOIN dbo.Customers c ON c.Id=p.CustomerId ORDER BY p.CreatedAt DESC",c);await using var r=await q.ExecuteReaderAsync();while(await r.ReadAsync())a.Add(new(r.GetGuid(0),r.GetString(1),r.GetString(2),r.GetDecimal(3),r.GetDecimal(4),r.GetString(5),r.IsDBNull(6)?null:r.GetString(6)));return a;}
 public async Task<List<InvoiceListRow>> Invoices(){var a=new List<InvoiceListRow>();await using var c=Open();await c.OpenAsync();await using var q=new SqlCommand("SELECT i.Id,i.Ikey,i.RequestedAmount,i.Status,c.Name,i.RequestedAt FROM dbo.InvoiceRequests i JOIN dbo.Customers c ON c.Id=i.CustomerId ORDER BY i.RequestedAt DESC",c);await using var r=await q.ExecuteReaderAsync();while(await r.ReadAsync())a.Add(new(r.GetGuid(0),r.GetString(1),r.GetDecimal(2),r.GetString(3),r.GetString(4),r.GetDateTime(5)));return a;}
 public async Task<List<CreditWalletRow>> Credits(){var a=new List<CreditWalletRow>();await using var c=Open();await c.OpenAsync();await using var q=new SqlCommand("SELECT p.Name,w.CreditType,w.CurrentBalance,w.ReservedBalance FROM dbo.PartnerCreditWallets w JOIN dbo.Partners p ON p.Id=w.PartnerId ORDER BY p.Name,w.CreditType",c);await using var r=await q.ExecuteReaderAsync();while(await r.ReadAsync())a.Add(new(r.GetString(0),r.GetString(1),r.GetDecimal(2),r.GetDecimal(3)));return a;}
 public async Task<List<ProviderRow>> Providers(){var a=new List<ProviderRow>();await using var c=Open();await c.OpenAsync();await using var q=new SqlCommand("SELECT Code,Name,ProviderType,IsActive FROM dbo.Providers ORDER BY ProviderType,Name",c);await using var r=await q.ExecuteReaderAsync();while(await r.ReadAsync())a.Add(new(r.GetString(0),r.GetString(1),r.GetString(2),r.GetBoolean(3)));return a;}
}
