/* TAPortal 010 - Provider, package, subscription and credit foundation. */
USE [TAPortal];
GO
IF OBJECT_ID(N'dbo.Providers',N'U') IS NULL CREATE TABLE dbo.Providers(Id uniqueidentifier NOT NULL CONSTRAINT PK_Providers PRIMARY KEY DEFAULT NEWSEQUENTIALID(),Code varchar(50) NOT NULL,Name nvarchar(200) NOT NULL,ProviderType varchar(30) NOT NULL,IsActive bit NOT NULL CONSTRAINT DF_Providers_Active DEFAULT 1,CreatedAt datetime2(3) NOT NULL CONSTRAINT DF_Providers_Created DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_Providers_Code UNIQUE(Code));
IF OBJECT_ID(N'dbo.PartnerProviderConnections',N'U') IS NULL CREATE TABLE dbo.PartnerProviderConnections(Id uniqueidentifier NOT NULL CONSTRAINT PK_PartnerProviderConnections PRIMARY KEY DEFAULT NEWSEQUENTIALID(),PartnerId uniqueidentifier NOT NULL,ProviderId uniqueidentifier NOT NULL,ExternalCompanyId nvarchar(200) NULL,Status varchar(30) NOT NULL CONSTRAINT DF_PPC_Status DEFAULT 'PENDING',ConfigJson nvarchar(max) NULL,SecretReference nvarchar(500) NULL,LastSyncedAt datetime2(3) NULL,CreatedAt datetime2(3) NOT NULL CONSTRAINT DF_PPC_Created DEFAULT SYSUTCDATETIME(),UpdatedAt datetime2(3) NULL,RowVersion rowversion NOT NULL,CONSTRAINT FK_PPC_Partner FOREIGN KEY(PartnerId) REFERENCES dbo.Partners(Id),CONSTRAINT FK_PPC_Provider FOREIGN KEY(ProviderId) REFERENCES dbo.Providers(Id),CONSTRAINT UQ_PPC UNIQUE(PartnerId,ProviderId));
GO
IF OBJECT_ID(N'dbo.Services',N'U') IS NULL CREATE TABLE dbo.Services(Id uniqueidentifier NOT NULL CONSTRAINT PK_Services PRIMARY KEY DEFAULT NEWSEQUENTIALID(),Code varchar(50) NOT NULL UNIQUE,Name nvarchar(200) NOT NULL,Unit varchar(30) NOT NULL,IsActive bit NOT NULL DEFAULT 1);
IF OBJECT_ID(N'dbo.Packages',N'U') IS NULL CREATE TABLE dbo.Packages(Id uniqueidentifier NOT NULL CONSTRAINT PK_Packages PRIMARY KEY DEFAULT NEWSEQUENTIALID(),Code varchar(50) NOT NULL UNIQUE,Name nvarchar(200) NOT NULL,BillingCycle varchar(20) NOT NULL,Price decimal(18,2) NOT NULL DEFAULT 0,IsActive bit NOT NULL DEFAULT 1,CONSTRAINT CK_Packages_Cycle CHECK(BillingCycle IN('MONTHLY','QUARTERLY','YEARLY','CUSTOM')));
IF OBJECT_ID(N'dbo.PackageServices',N'U') IS NULL CREATE TABLE dbo.PackageServices(PackageId uniqueidentifier NOT NULL,ServiceId uniqueidentifier NOT NULL,IncludedQuantity decimal(18,2) NULL,CONSTRAINT PK_PackageServices PRIMARY KEY(PackageId,ServiceId),CONSTRAINT FK_PS_Package FOREIGN KEY(PackageId) REFERENCES dbo.Packages(Id),CONSTRAINT FK_PS_Service FOREIGN KEY(ServiceId) REFERENCES dbo.Services(Id));
IF OBJECT_ID(N'dbo.PartnerSubscriptions',N'U') IS NULL CREATE TABLE dbo.PartnerSubscriptions(Id uniqueidentifier NOT NULL CONSTRAINT PK_PartnerSubscriptions PRIMARY KEY DEFAULT NEWSEQUENTIALID(),PartnerId uniqueidentifier NOT NULL,PackageId uniqueidentifier NOT NULL,Status varchar(20) NOT NULL,StartsAt datetime2(3) NOT NULL,EndsAt datetime2(3) NULL,CreatedAt datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT FK_Sub_Partner FOREIGN KEY(PartnerId) REFERENCES dbo.Partners(Id),CONSTRAINT FK_Sub_Package FOREIGN KEY(PackageId) REFERENCES dbo.Packages(Id));
IF OBJECT_ID(N'dbo.PartnerCreditWallets',N'U') IS NULL CREATE TABLE dbo.PartnerCreditWallets(Id uniqueidentifier NOT NULL CONSTRAINT PK_CreditWallet PRIMARY KEY DEFAULT NEWSEQUENTIALID(),PartnerId uniqueidentifier NOT NULL,CreditType varchar(20) NOT NULL,CurrentBalance decimal(18,2) NOT NULL DEFAULT 0,ReservedBalance decimal(18,2) NOT NULL DEFAULT 0,RowVersion rowversion NOT NULL,CONSTRAINT FK_Wallet_Partner FOREIGN KEY(PartnerId) REFERENCES dbo.Partners(Id),CONSTRAINT UQ_Wallet UNIQUE(PartnerId,CreditType),CONSTRAINT CK_Wallet_Type CHECK(CreditType IN('BANKING','EINVOICE')));
IF OBJECT_ID(N'dbo.CreditLedger',N'U') IS NULL CREATE TABLE dbo.CreditLedger(Id bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_CreditLedger PRIMARY KEY,PartnerId uniqueidentifier NOT NULL,CreditType varchar(20) NOT NULL,EntryType varchar(20) NOT NULL,Quantity decimal(18,2) NOT NULL,BalanceAfter decimal(18,2) NOT NULL,SourceType varchar(50) NULL,SourceId nvarchar(200) NULL,IdempotencyKey nvarchar(200) NULL,ExpiresAt datetime2(3) NULL,Description nvarchar(500) NULL,CreatedAt datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT FK_Ledger_Partner FOREIGN KEY(PartnerId) REFERENCES dbo.Partners(Id),CONSTRAINT CK_Ledger_Type CHECK(CreditType IN('BANKING','EINVOICE')),CONSTRAINT CK_Ledger_Entry CHECK(EntryType IN('GRANT','CONSUME','REFUND','ADJUST','EXPIRE','RESERVE','RELEASE')));
GO
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID('dbo.CreditLedger') AND name='UX_CreditLedger_Idempotency') CREATE UNIQUE INDEX UX_CreditLedger_Idempotency ON dbo.CreditLedger(PartnerId,IdempotencyKey) WHERE IdempotencyKey IS NOT NULL;
IF EXISTS(SELECT 1 FROM dbo.Providers WHERE Code='SEPAY_BANKHUB') UPDATE dbo.Providers SET Name=N'SePay Bank Hub',ProviderType='BANKING',IsActive=1 WHERE Code='SEPAY_BANKHUB'; ELSE INSERT dbo.Providers(Code,Name,ProviderType) VALUES('SEPAY_BANKHUB',N'SePay Bank Hub','BANKING');
IF EXISTS(SELECT 1 FROM dbo.Providers WHERE Code='EASYINVOICE') UPDATE dbo.Providers SET Name=N'EasyInvoice',ProviderType='EINVOICE',IsActive=1 WHERE Code='EASYINVOICE'; ELSE INSERT dbo.Providers(Code,Name,ProviderType) VALUES('EASYINVOICE',N'EasyInvoice','EINVOICE');
IF EXISTS(SELECT 1 FROM dbo.Services WHERE Code='BANKING') UPDATE dbo.Services SET Name=N'Giao dịch ngân hàng',Unit='TRANSACTION',IsActive=1 WHERE Code='BANKING'; ELSE INSERT dbo.Services(Code,Name,Unit) VALUES('BANKING',N'Giao dịch ngân hàng','TRANSACTION');
IF EXISTS(SELECT 1 FROM dbo.Services WHERE Code='EINVOICE') UPDATE dbo.Services SET Name=N'Hóa đơn điện tử',Unit='INVOICE',IsActive=1 WHERE Code='EINVOICE'; ELSE INSERT dbo.Services(Code,Name,Unit) VALUES('EINVOICE',N'Hóa đơn điện tử','INVOICE');
IF EXISTS(SELECT 1 FROM dbo.Services WHERE Code='BANK_CONNECT') UPDATE dbo.Services SET Name=N'Kết nối ngân hàng',Unit='ACCOUNT',IsActive=1 WHERE Code='BANK_CONNECT'; ELSE INSERT dbo.Services(Code,Name,Unit) VALUES('BANK_CONNECT',N'Kết nối ngân hàng','ACCOUNT');
IF EXISTS(SELECT 1 FROM dbo.Services WHERE Code='QR') UPDATE dbo.Services SET Name=N'QR thanh toán',Unit='REQUEST',IsActive=1 WHERE Code='QR'; ELSE INSERT dbo.Services(Code,Name,Unit) VALUES('QR',N'QR thanh toán','REQUEST');
GO
PRINT '010-provider-billing-foundation.sql: OK';
GO