/* TAPortal 011 - Banking ingestion/reconciliation core. */
USE [TAPortal];
GO
IF OBJECT_ID(N'dbo.PartnerBankAccounts',N'U') IS NULL CREATE TABLE dbo.PartnerBankAccounts(Id uniqueidentifier NOT NULL CONSTRAINT PK_PartnerBankAccounts PRIMARY KEY DEFAULT NEWSEQUENTIALID(),PartnerId uniqueidentifier NOT NULL,ProviderId uniqueidentifier NOT NULL,ExternalBankAccountId nvarchar(200) NULL,BankCode varchar(30) NOT NULL,BankName nvarchar(200) NULL,AccountNumber nvarchar(100) NOT NULL,AccountHolderName nvarchar(250) NULL,AccountType varchar(30) NULL,BankApiConnected bit NOT NULL DEFAULT 0,Status varchar(30) NOT NULL DEFAULT 'ACTIVE',LastTransactionAt datetime2(3) NULL,CreatedAt datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME(),UpdatedAt datetime2(3) NULL,RowVersion rowversion NOT NULL,CONSTRAINT FK_PBA_Partner FOREIGN KEY(PartnerId) REFERENCES dbo.Partners(Id),CONSTRAINT FK_PBA_Provider FOREIGN KEY(ProviderId) REFERENCES dbo.Providers(Id));
IF OBJECT_ID(N'dbo.BankWebhookEvents',N'U') IS NULL CREATE TABLE dbo.BankWebhookEvents(Id bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_BankWebhookEvents PRIMARY KEY,PartnerId uniqueidentifier NULL,ProviderId uniqueidentifier NOT NULL,ExternalEventId nvarchar(200) NULL,EventType varchar(50) NULL,SignatureValid bit NULL,ProcessingStatus varchar(30) NOT NULL DEFAULT 'RECEIVED',RawPayload nvarchar(max) NOT NULL,ErrorMessage nvarchar(2000) NULL,ReceivedAt datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME(),ProcessedAt datetime2(3) NULL,CONSTRAINT FK_BWE_Partner FOREIGN KEY(PartnerId) REFERENCES dbo.Partners(Id),CONSTRAINT FK_BWE_Provider FOREIGN KEY(ProviderId) REFERENCES dbo.Providers(Id));
IF OBJECT_ID(N'dbo.BankTransactions',N'U') IS NULL CREATE TABLE dbo.BankTransactions(Id uniqueidentifier NOT NULL CONSTRAINT PK_BankTransactions PRIMARY KEY DEFAULT NEWSEQUENTIALID(),PartnerId uniqueidentifier NOT NULL,ProviderId uniqueidentifier NOT NULL,BankAccountId uniqueidentifier NOT NULL,ExternalTransactionId nvarchar(200) NOT NULL,TransactionDate datetime2(3) NOT NULL,Direction varchar(10) NOT NULL,Amount decimal(18,2) NOT NULL,ReferenceNumber nvarchar(200) NULL,Content nvarchar(1000) NULL,PaymentCode varchar(100) NULL,CounterpartyAccount nvarchar(150) NULL,CounterpartyName nvarchar(250) NULL,Source varchar(30) NOT NULL,RawPayload nvarchar(max) NULL,CreatedAt datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT FK_BT_Partner FOREIGN KEY(PartnerId) REFERENCES dbo.Partners(Id),CONSTRAINT FK_BT_Provider FOREIGN KEY(ProviderId) REFERENCES dbo.Providers(Id),CONSTRAINT FK_BT_Account FOREIGN KEY(BankAccountId) REFERENCES dbo.PartnerBankAccounts(Id),CONSTRAINT CK_BT_Direction CHECK(Direction IN('CREDIT','DEBIT')),CONSTRAINT CK_BT_Source CHECK(Source IN('IPN','RECONCILIATION','IMPORT')));
IF OBJECT_ID(N'dbo.BankSyncJobs',N'U') IS NULL CREATE TABLE dbo.BankSyncJobs(Id uniqueidentifier NOT NULL CONSTRAINT PK_BankSyncJobs PRIMARY KEY DEFAULT NEWSEQUENTIALID(),PartnerId uniqueidentifier NOT NULL,ProviderId uniqueidentifier NOT NULL,BankAccountId uniqueidentifier NULL,FromDate datetime2(3) NOT NULL,ToDate datetime2(3) NOT NULL,Status varchar(30) NOT NULL DEFAULT 'PENDING',TransactionsFound int NOT NULL DEFAULT 0,StartedAt datetime2(3) NULL,CompletedAt datetime2(3) NULL,ErrorMessage nvarchar(2000) NULL,CreatedAt datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT FK_BSJ_Partner FOREIGN KEY(PartnerId) REFERENCES dbo.Partners(Id),CONSTRAINT FK_BSJ_Provider FOREIGN KEY(ProviderId) REFERENCES dbo.Providers(Id),CONSTRAINT FK_BSJ_Account FOREIGN KEY(BankAccountId) REFERENCES dbo.PartnerBankAccounts(Id));
GO
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID('dbo.BankTransactions') AND name='UX_BT_ProviderExternal') CREATE UNIQUE INDEX UX_BT_ProviderExternal ON dbo.BankTransactions(ProviderId,ExternalTransactionId);
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID('dbo.BankTransactions') AND name='IX_BT_PartnerDate') CREATE INDEX IX_BT_PartnerDate ON dbo.BankTransactions(PartnerId,TransactionDate DESC) INCLUDE(Amount,Direction,PaymentCode,BankAccountId);
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID('dbo.BankTransactions') AND name='IX_BT_PaymentCode') CREATE INDEX IX_BT_PaymentCode ON dbo.BankTransactions(PartnerId,PaymentCode) INCLUDE(Amount,TransactionDate) WHERE PaymentCode IS NOT NULL;
GO
PRINT '011-banking-core.sql: OK';
GO