/* TAPortal 012 - Payment request, multi-payment allocation and matching. */
USE [TAPortal];
GO
IF OBJECT_ID(N'dbo.PaymentRequests',N'U') IS NULL CREATE TABLE dbo.PaymentRequests(Id uniqueidentifier NOT NULL CONSTRAINT PK_PaymentRequests PRIMARY KEY DEFAULT NEWSEQUENTIALID(),PartnerId uniqueidentifier NOT NULL,CustomerId uniqueidentifier NULL,Code varchar(50) NOT NULL,PaymentCode varchar(100) NOT NULL,Description nvarchar(500) NULL,AmountDue decimal(18,2) NOT NULL,AmountPaid decimal(18,2) NOT NULL DEFAULT 0,Status varchar(30) NOT NULL DEFAULT 'PENDING',ExpiresAt datetime2(3) NULL,ClosedAt datetime2(3) NULL,CreatedAt datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME(),UpdatedAt datetime2(3) NULL,RowVersion rowversion NOT NULL,CONSTRAINT FK_PR_Partner FOREIGN KEY(PartnerId) REFERENCES dbo.Partners(Id),CONSTRAINT FK_PR_Customer FOREIGN KEY(CustomerId) REFERENCES dbo.Customers(Id),CONSTRAINT CK_PR_Amount CHECK(AmountDue>0 AND AmountPaid>=0),CONSTRAINT CK_PR_Status CHECK(Status IN('PENDING','PARTIALLY_PAID','PAID','OVERPAID','EXPIRED','CANCELLED','NEEDS_REVIEW')));
IF OBJECT_ID(N'dbo.PaymentAllocations',N'U') IS NULL CREATE TABLE dbo.PaymentAllocations(Id uniqueidentifier NOT NULL CONSTRAINT PK_PaymentAllocations PRIMARY KEY DEFAULT NEWSEQUENTIALID(),PaymentRequestId uniqueidentifier NOT NULL,BankTransactionId uniqueidentifier NOT NULL,AllocatedAmount decimal(18,2) NOT NULL,Status varchar(20) NOT NULL DEFAULT 'ACTIVE',AllocatedAt datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME(),ReversedAt datetime2(3) NULL,ReversalReason nvarchar(500) NULL,CONSTRAINT FK_PA_Request FOREIGN KEY(PaymentRequestId) REFERENCES dbo.PaymentRequests(Id),CONSTRAINT FK_PA_Transaction FOREIGN KEY(BankTransactionId) REFERENCES dbo.BankTransactions(Id),CONSTRAINT CK_PA_Amount CHECK(AllocatedAmount>0),CONSTRAINT CK_PA_Status CHECK(Status IN('ACTIVE','REVERSED')));
IF OBJECT_ID(N'dbo.TransactionMatches',N'U') IS NULL CREATE TABLE dbo.TransactionMatches(Id uniqueidentifier NOT NULL CONSTRAINT PK_TransactionMatches PRIMARY KEY DEFAULT NEWSEQUENTIALID(),BankTransactionId uniqueidentifier NOT NULL,CustomerId uniqueidentifier NULL,PaymentRequestId uniqueidentifier NULL,MatchMethod varchar(30) NOT NULL,Confidence decimal(5,2) NULL,Status varchar(20) NOT NULL DEFAULT 'SUGGESTED',Reason nvarchar(500) NULL,CreatedAt datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME(),ConfirmedAt datetime2(3) NULL,CONSTRAINT FK_TM_Transaction FOREIGN KEY(BankTransactionId) REFERENCES dbo.BankTransactions(Id),CONSTRAINT FK_TM_Customer FOREIGN KEY(CustomerId) REFERENCES dbo.Customers(Id),CONSTRAINT FK_TM_Request FOREIGN KEY(PaymentRequestId) REFERENCES dbo.PaymentRequests(Id),CONSTRAINT CK_TM_Method CHECK(MatchMethod IN('SENDER_ACCOUNT','PAYMENT_CODE','CONTENT','AMOUNT','CUSTOMER_CODE','HISTORY','MANUAL','RULE')),CONSTRAINT CK_TM_Status CHECK(Status IN('SUGGESTED','MATCHED','CONFIRMED','REJECTED')));
GO
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID('dbo.PaymentRequests') AND name='UX_PR_PartnerPaymentCode') CREATE UNIQUE INDEX UX_PR_PartnerPaymentCode ON dbo.PaymentRequests(PartnerId,PaymentCode);
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID('dbo.PaymentAllocations') AND name='UX_PA_RequestTransactionActive') CREATE UNIQUE INDEX UX_PA_RequestTransactionActive ON dbo.PaymentAllocations(PaymentRequestId,BankTransactionId) WHERE Status='ACTIVE';
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID('dbo.PaymentAllocations') AND name='IX_PA_Transaction') CREATE INDEX IX_PA_Transaction ON dbo.PaymentAllocations(BankTransactionId,Status) INCLUDE(PaymentRequestId,AllocatedAmount);
GO
PRINT '012-payment-reconciliation.sql: OK';
GO