/* TAPortal 013 - Invoice workflow foundation. */
USE [TAPortal];
GO
IF OBJECT_ID(N'dbo.CustomerInvoicePolicies',N'U') IS NULL CREATE TABLE dbo.CustomerInvoicePolicies(CustomerId uniqueidentifier NOT NULL CONSTRAINT PK_CustomerInvoicePolicies PRIMARY KEY,Mode varchar(20) NOT NULL DEFAULT 'REVIEW',IsActive bit NOT NULL DEFAULT 1,UpdatedAt datetime2(3) NULL,CONSTRAINT FK_CIP_Customer FOREIGN KEY(CustomerId) REFERENCES dbo.Customers(Id),CONSTRAINT CK_CIP_Mode CHECK(Mode IN('AUTO','REVIEW','MANUAL')));
IF OBJECT_ID(N'dbo.InvoiceRequests',N'U') IS NULL CREATE TABLE dbo.InvoiceRequests(Id uniqueidentifier NOT NULL CONSTRAINT PK_InvoiceRequests PRIMARY KEY DEFAULT NEWSEQUENTIALID(),PartnerId uniqueidentifier NOT NULL,CustomerId uniqueidentifier NOT NULL,PaymentRequestId uniqueidentifier NULL,Status varchar(30) NOT NULL DEFAULT 'PENDING_REVIEW',RequestedAmount decimal(18,2) NOT NULL,Ikey nvarchar(200) NOT NULL,RequestedAt datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME(),ErrorMessage nvarchar(2000) NULL,CONSTRAINT FK_IR_Partner FOREIGN KEY(PartnerId) REFERENCES dbo.Partners(Id),CONSTRAINT FK_IR_Customer FOREIGN KEY(CustomerId) REFERENCES dbo.Customers(Id),CONSTRAINT FK_IR_Payment FOREIGN KEY(PaymentRequestId) REFERENCES dbo.PaymentRequests(Id),CONSTRAINT CK_IR_Status CHECK(Status IN('PENDING_REVIEW','READY','QUEUED','ISSUED','FAILED','CANCELLED')));
IF OBJECT_ID(N'dbo.Invoices',N'U') IS NULL CREATE TABLE dbo.Invoices(Id uniqueidentifier NOT NULL CONSTRAINT PK_Invoices PRIMARY KEY DEFAULT NEWSEQUENTIALID(),PartnerId uniqueidentifier NOT NULL,InvoiceRequestId uniqueidentifier NOT NULL,ProviderId uniqueidentifier NOT NULL,ExternalInvoiceId nvarchar(200) NULL,InvoiceNo nvarchar(100) NULL,Ikey nvarchar(200) NOT NULL,TotalAmount decimal(18,2) NOT NULL,Status varchar(30) NOT NULL,IssuedAt datetime2(3) NULL,CreatedAt datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT FK_Inv_Partner FOREIGN KEY(PartnerId) REFERENCES dbo.Partners(Id),CONSTRAINT FK_Inv_Request FOREIGN KEY(InvoiceRequestId) REFERENCES dbo.InvoiceRequests(Id),CONSTRAINT FK_Inv_Provider FOREIGN KEY(ProviderId) REFERENCES dbo.Providers(Id));
IF OBJECT_ID(N'dbo.InvoiceItems',N'U') IS NULL CREATE TABLE dbo.InvoiceItems(Id uniqueidentifier NOT NULL CONSTRAINT PK_InvoiceItems PRIMARY KEY DEFAULT NEWSEQUENTIALID(),InvoiceRequestId uniqueidentifier NOT NULL,ItemName nvarchar(500) NOT NULL,Unit nvarchar(50) NULL,Quantity decimal(18,4) NOT NULL,UnitPrice decimal(18,2) NOT NULL,VatRate decimal(8,4) NULL,Amount decimal(18,2) NOT NULL,SortOrder int NOT NULL DEFAULT 0,CONSTRAINT FK_II_Request FOREIGN KEY(InvoiceRequestId) REFERENCES dbo.InvoiceRequests(Id));
IF OBJECT_ID(N'dbo.InvoiceIntegrationLogs',N'U') IS NULL CREATE TABLE dbo.InvoiceIntegrationLogs(Id bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_InvoiceIntegrationLogs PRIMARY KEY,InvoiceRequestId uniqueidentifier NOT NULL,ProviderId uniqueidentifier NOT NULL,Operation varchar(50) NOT NULL,Success bit NOT NULL,RequestPayload nvarchar(max) NULL,ResponsePayload nvarchar(max) NULL,ErrorMessage nvarchar(2000) NULL,CreatedAt datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT FK_IIL_Request FOREIGN KEY(InvoiceRequestId) REFERENCES dbo.InvoiceRequests(Id),CONSTRAINT FK_IIL_Provider FOREIGN KEY(ProviderId) REFERENCES dbo.Providers(Id));
IF OBJECT_ID(N'dbo.InvoiceFiles',N'U') IS NULL CREATE TABLE dbo.InvoiceFiles(Id uniqueidentifier NOT NULL CONSTRAINT PK_InvoiceFiles PRIMARY KEY DEFAULT NEWSEQUENTIALID(),InvoiceId uniqueidentifier NOT NULL,FileType varchar(20) NOT NULL,StoragePath nvarchar(1000) NOT NULL,CreatedAt datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT FK_IF_Invoice FOREIGN KEY(InvoiceId) REFERENCES dbo.Invoices(Id));
GO
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID('dbo.InvoiceRequests') AND name='UX_IR_PartnerIkey') CREATE UNIQUE INDEX UX_IR_PartnerIkey ON dbo.InvoiceRequests(PartnerId,Ikey);
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID('dbo.Invoices') AND name='UX_Inv_PartnerIkey') CREATE UNIQUE INDEX UX_Inv_PartnerIkey ON dbo.Invoices(PartnerId,Ikey);
GO
PRINT '013-invoice-core.sql: OK';
GO