/* TAPortal 014 - Feature modules, permissions and navigation. Run after 009-013. */
USE [TAPortal];
GO
MERGE dbo.Modules T USING(VALUES('PARTNER',N'Đối tác',20),('BANKING',N'Ngân hàng & thanh toán',40),('INVOICE',N'Hóa đơn',50),('BILLING',N'Gói dịch vụ',60),('INTEGRATION',N'Tích hợp',70))S(Code,Name,SortOrder) ON T.Code=S.Code AND T.IsDeleted=0 WHEN MATCHED THEN UPDATE SET Name=S.Name,SortOrder=S.SortOrder,IsActive=1 WHEN NOT MATCHED THEN INSERT(Code,Name,SortOrder,IsActive) VALUES(S.Code,S.Name,S.SortOrder,1);
GO
DECLARE @Partner uniqueidentifier=(SELECT TOP 1 Id FROM dbo.Modules WHERE Code='PARTNER' AND IsDeleted=0),@Bank uniqueidentifier=(SELECT TOP 1 Id FROM dbo.Modules WHERE Code='BANKING' AND IsDeleted=0),@Inv uniqueidentifier=(SELECT TOP 1 Id FROM dbo.Modules WHERE Code='INVOICE' AND IsDeleted=0),@Bill uniqueidentifier=(SELECT TOP 1 Id FROM dbo.Modules WHERE Code='BILLING' AND IsDeleted=0),@Int uniqueidentifier=(SELECT TOP 1 Id FROM dbo.Modules WHERE Code='INTEGRATION' AND IsDeleted=0);
MERGE dbo.Functions T USING(VALUES(@Partner,'PARTNERS',N'Đối tác','/partners',10),(@Bank,'BANK_ACCOUNTS',N'Tài khoản ngân hàng','/banking/accounts',10),(@Bank,'TRANSACTIONS',N'Giao dịch ngân hàng','/banking/transactions',20),(@Bank,'PAYMENTS',N'Yêu cầu thanh toán','/payments',30),(@Inv,'INVOICES',N'Hóa đơn','/invoices',10),(@Bill,'CREDITS',N'Số dư Credit','/billing/credits',10),(@Int,'PROVIDERS',N'Nhà cung cấp','/integrations/providers',10))S(ModuleId,Code,Name,Route,SortOrder) ON T.ModuleId=S.ModuleId AND T.Code=S.Code AND T.IsDeleted=0 WHEN MATCHED THEN UPDATE SET Name=S.Name,Route=S.Route,SortOrder=S.SortOrder,IsActive=1 WHEN NOT MATCHED THEN INSERT(ModuleId,Code,Name,Route,SortOrder,IsActive) VALUES(S.ModuleId,S.Code,S.Name,S.Route,S.SortOrder,1);
GO
MERGE dbo.Permissions T USING(VALUES('PARTNER.PARTNERS.VIEW',N'Xem đối tác','PARTNER','PARTNERS','VIEW'),('BANKING.BANK_ACCOUNTS.VIEW',N'Xem tài khoản ngân hàng','BANKING','BANK_ACCOUNTS','VIEW'),('BANKING.TRANSACTIONS.VIEW',N'Xem giao dịch ngân hàng','BANKING','TRANSACTIONS','VIEW'),('BANKING.PAYMENTS.VIEW',N'Xem yêu cầu thanh toán','BANKING','PAYMENTS','VIEW'),('INVOICE.INVOICES.VIEW',N'Xem hóa đơn','INVOICE','INVOICES','VIEW'),('BILLING.CREDITS.VIEW',N'Xem số dư credit','BILLING','CREDITS','VIEW'),('INTEGRATION.PROVIDERS.VIEW',N'Xem nhà cung cấp','INTEGRATION','PROVIDERS','VIEW'))S(Code,Name,ModuleCode,FunctionCode,ActionCode) ON T.Code=S.Code AND T.IsDeleted=0 WHEN MATCHED THEN UPDATE SET Name=S.Name,IsActive=1 WHEN NOT MATCHED THEN INSERT(Code,Name,ModuleCode,FunctionCode,ActionCode,IsSystem,IsActive) VALUES(S.Code,S.Name,S.ModuleCode,S.FunctionCode,S.ActionCode,1,1);
GO
DECLARE @CrmGroup uniqueidentifier=(SELECT TOP 1 Id FROM dbo.Menus WHERE Code='CRM_GROUP' AND IsDeleted=0),@BankGroup uniqueidentifier=(SELECT TOP 1 Id FROM dbo.Menus WHERE Code='BANKING_GROUP' AND IsDeleted=0),@InvGroup uniqueidentifier=(SELECT TOP 1 Id FROM dbo.Menus WHERE Code='INVOICE_GROUP' AND IsDeleted=0),@BillGroup uniqueidentifier=(SELECT TOP 1 Id FROM dbo.Menus WHERE Code='BILLING_GROUP' AND IsDeleted=0),@IntGroup uniqueidentifier=(SELECT TOP 1 Id FROM dbo.Menus WHERE Code='INTEGRATION_GROUP' AND IsDeleted=0);
UPDATE dbo.Menus SET IsVisible=1 WHERE Code IN('BANKING_GROUP','INVOICE_GROUP','BILLING_GROUP','INTEGRATION_GROUP') AND IsDeleted=0;
DECLARE @PartnerFn uniqueidentifier=(SELECT TOP 1 Id FROM dbo.Functions WHERE Code='PARTNERS' AND IsDeleted=0),@AccFn uniqueidentifier=(SELECT TOP 1 Id FROM dbo.Functions WHERE Code='BANK_ACCOUNTS' AND IsDeleted=0),@TxFn uniqueidentifier=(SELECT TOP 1 Id FROM dbo.Functions WHERE Code='TRANSACTIONS' AND IsDeleted=0),@PayFn uniqueidentifier=(SELECT TOP 1 Id FROM dbo.Functions WHERE Code='PAYMENTS' AND IsDeleted=0),@InvFn uniqueidentifier=(SELECT TOP 1 Id FROM dbo.Functions WHERE Code='INVOICES' AND IsDeleted=0),@CreditFn uniqueidentifier=(SELECT TOP 1 Id FROM dbo.Functions WHERE Code='CREDITS' AND IsDeleted=0),@ProviderFn uniqueidentifier=(SELECT TOP 1 Id FROM dbo.Functions WHERE Code='PROVIDERS' AND IsDeleted=0);
MERGE dbo.Menus T USING(VALUES(@CrmGroup,@PartnerFn,'PARTNERS',N'Đối tác','ti ti-building-community','/partners',5),(@BankGroup,@AccFn,'BANK_ACCOUNTS',N'Tài khoản ngân hàng','ti ti-building-bank','/banking/accounts',10),(@BankGroup,@TxFn,'BANK_TRANSACTIONS',N'Giao dịch ngân hàng','ti ti-arrows-exchange','/banking/transactions',20),(@BankGroup,@PayFn,'PAYMENT_REQUESTS',N'Yêu cầu thanh toán','ti ti-qrcode','/payments',30),(@InvGroup,@InvFn,'INVOICES',N'Hóa đơn','ti ti-receipt-2','/invoices',10),(@BillGroup,@CreditFn,'CREDITS',N'Số dư Credit','ti ti-coins','/billing/credits',10),(@IntGroup,@ProviderFn,'PROVIDERS',N'Nhà cung cấp','ti ti-plug-connected','/integrations/providers',10))S(ParentId,FunctionId,Code,Name,Icon,Route,SortOrder) ON T.Code=S.Code AND T.IsDeleted=0 WHEN MATCHED THEN UPDATE SET ParentId=S.ParentId,FunctionId=S.FunctionId,Name=S.Name,Icon=S.Icon,Route=S.Route,SortOrder=S.SortOrder,IsVisible=1,IsActive=1 WHEN NOT MATCHED THEN INSERT(ParentId,FunctionId,Code,Name,Icon,Route,SortOrder,IsVisible,IsActive) VALUES(S.ParentId,S.FunctionId,S.Code,S.Name,S.Icon,S.Route,S.SortOrder,1,1);
GO
INSERT dbo.MenuPermissions(MenuId,PermissionId) SELECT m.Id,p.Id FROM dbo.Menus m JOIN dbo.Permissions p ON p.Code=CASE m.Code WHEN 'PARTNERS' THEN 'PARTNER.PARTNERS.VIEW' WHEN 'BANK_ACCOUNTS' THEN 'BANKING.BANK_ACCOUNTS.VIEW' WHEN 'BANK_TRANSACTIONS' THEN 'BANKING.TRANSACTIONS.VIEW' WHEN 'PAYMENT_REQUESTS' THEN 'BANKING.PAYMENTS.VIEW' WHEN 'INVOICES' THEN 'INVOICE.INVOICES.VIEW' WHEN 'CREDITS' THEN 'BILLING.CREDITS.VIEW' WHEN 'PROVIDERS' THEN 'INTEGRATION.PROVIDERS.VIEW' END WHERE m.Code IN('PARTNERS','BANK_ACCOUNTS','BANK_TRANSACTIONS','PAYMENT_REQUESTS','INVOICES','CREDITS','PROVIDERS') AND NOT EXISTS(SELECT 1 FROM dbo.MenuPermissions mp WHERE mp.MenuId=m.Id AND mp.PermissionId=p.Id);
DECLARE @Admin uniqueidentifier=(SELECT TOP 1 Id FROM dbo.Roles WHERE Code='SYS_ADMIN' AND IsDeleted=0); IF @Admin IS NOT NULL INSERT dbo.RolePermissions(RoleId,PermissionId) SELECT @Admin,p.Id FROM dbo.Permissions p WHERE p.IsDeleted=0 AND NOT EXISTS(SELECT 1 FROM dbo.RolePermissions rp WHERE rp.RoleId=@Admin AND rp.PermissionId=p.Id);
GO
PRINT '014-feature-navigation-permissions.sql: OK';
GO