/* RC2 032 - Unapplied customer cash, refund lifecycle and explicit dispositions. */
USE [TAPortal]; GO
IF OBJECT_ID(N'dbo.CustomerCashAccounts',N'U') IS NULL BEGIN
 CREATE TABLE dbo.CustomerCashAccounts(Id uniqueidentifier NOT NULL DEFAULT NEWSEQUENTIALID() CONSTRAINT PK_CustomerCashAccounts PRIMARY KEY,PartnerId uniqueidentifier NOT NULL,CompanyId uniqueidentifier NULL,CustomerId uniqueidentifier NOT NULL,CurrencyCode char(3) NOT NULL DEFAULT 'VND',Balance decimal(18,2) NOT NULL DEFAULT 0,CreatedAt datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME(),RowVersion rowversion NOT NULL,CONSTRAINT FK_CCA_Partner FOREIGN KEY(PartnerId) REFERENCES dbo.Partners(Id),CONSTRAINT FK_CCA_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Companies(Id),CONSTRAINT FK_CCA_Customer FOREIGN KEY(CustomerId) REFERENCES dbo.Customers(Id));
 CREATE UNIQUE INDEX UX_CCA_OwnerCurrency ON dbo.CustomerCashAccounts(PartnerId,CompanyId,CustomerId,CurrencyCode);
END
IF OBJECT_ID(N'dbo.CustomerCashLedger',N'U') IS NULL BEGIN
 CREATE TABLE dbo.CustomerCashLedger(Id bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_CustomerCashLedger PRIMARY KEY,CustomerCashAccountId uniqueidentifier NOT NULL,EntryType varchar(20) NOT NULL,Amount decimal(18,2) NOT NULL,BalanceAfter decimal(18,2) NOT NULL,PaymentTransactionId uniqueidentifier NULL,ReferenceType varchar(40) NULL,ReferenceId nvarchar(200) NULL,Reason nvarchar(500) NULL,ActorId uniqueidentifier NULL,CreatedAt datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT FK_CCL_Account FOREIGN KEY(CustomerCashAccountId) REFERENCES dbo.CustomerCashAccounts(Id),CONSTRAINT FK_CCL_Transaction FOREIGN KEY(PaymentTransactionId) REFERENCES dbo.PaymentTransactions(Id),CONSTRAINT CK_CCL_Type CHECK(EntryType IN('UNAPPLIED','APPLY','REFUND','ADJUST','REVERSAL')),CONSTRAINT CK_CCL_NonZero CHECK(Amount<>0));
 CREATE INDEX IX_CCL_AccountCreated ON dbo.CustomerCashLedger(CustomerCashAccountId,CreatedAt DESC);
END
IF OBJECT_ID(N'dbo.RefundRequests',N'U') IS NULL BEGIN
 CREATE TABLE dbo.RefundRequests(Id uniqueidentifier NOT NULL DEFAULT NEWSEQUENTIALID() CONSTRAINT PK_RefundRequests PRIMARY KEY,PartnerId uniqueidentifier NOT NULL,CompanyId uniqueidentifier NULL,CustomerId uniqueidentifier NULL,PaymentTransactionId uniqueidentifier NULL,CustomerCashAccountId uniqueidentifier NULL,Amount decimal(18,2) NOT NULL,CurrencyCode char(3) NOT NULL DEFAULT 'VND',Reason nvarchar(1000) NOT NULL,Status varchar(20) NOT NULL DEFAULT 'REQUESTED',RequestedBy uniqueidentifier NULL,RequestedAt datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME(),ApprovedBy uniqueidentifier NULL,ApprovedAt datetime2(3) NULL,CompletedAt datetime2(3) NULL,CONSTRAINT FK_RR_Partner FOREIGN KEY(PartnerId) REFERENCES dbo.Partners(Id),CONSTRAINT FK_RR_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Companies(Id),CONSTRAINT FK_RR_Customer FOREIGN KEY(CustomerId) REFERENCES dbo.Customers(Id),CONSTRAINT FK_RR_Transaction FOREIGN KEY(PaymentTransactionId) REFERENCES dbo.PaymentTransactions(Id),CONSTRAINT FK_RR_Cash FOREIGN KEY(CustomerCashAccountId) REFERENCES dbo.CustomerCashAccounts(Id),CONSTRAINT CK_RR_Amount CHECK(Amount>0),CONSTRAINT CK_RR_Status CHECK(Status IN('REQUESTED','APPROVED','REJECTED','PROCESSING','COMPLETED','FAILED','CANCELLED')));
END
IF OBJECT_ID(N'dbo.RefundOperations',N'U') IS NULL CREATE TABLE dbo.RefundOperations(Id uniqueidentifier NOT NULL DEFAULT NEWSEQUENTIALID() CONSTRAINT PK_RefundOperations PRIMARY KEY,RefundRequestId uniqueidentifier NOT NULL,ProviderId uniqueidentifier NULL,IdempotencyKey nvarchar(200) NOT NULL,Status varchar(20) NOT NULL DEFAULT 'PENDING',ExternalOperationId nvarchar(200) NULL,AttemptCount int NOT NULL DEFAULT 0,LastError nvarchar(2000) NULL,CreatedAt datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CompletedAt datetime2(3) NULL,CONSTRAINT FK_RO_Request FOREIGN KEY(RefundRequestId) REFERENCES dbo.RefundRequests(Id),CONSTRAINT FK_RO_Provider FOREIGN KEY(ProviderId) REFERENCES dbo.Providers(Id),CONSTRAINT UQ_RO_Idem UNIQUE(RefundRequestId,IdempotencyKey));
GO
PRINT '032-customer-cash-refund-disposition.sql: OK'; GO