/* RC2 033 - Explainable matching and review decision history. */
USE [TAPortal]; GO
IF OBJECT_ID(N'dbo.MatchingAttempts',N'U') IS NULL BEGIN
 CREATE TABLE dbo.MatchingAttempts(Id uniqueidentifier NOT NULL DEFAULT NEWSEQUENTIALID() CONSTRAINT PK_MatchingAttempts PRIMARY KEY,PartnerId uniqueidentifier NOT NULL,PaymentTransactionId uniqueidentifier NOT NULL,RuleSetHash varchar(128) NULL,Status varchar(20) NOT NULL,StartedAt datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CompletedAt datetime2(3) NULL,SelectedPaymentRequestId uniqueidentifier NULL,SelectedCustomerId uniqueidentifier NULL,CONSTRAINT FK_MA_Partner FOREIGN KEY(PartnerId) REFERENCES dbo.Partners(Id),CONSTRAINT FK_MA_Transaction FOREIGN KEY(PaymentTransactionId) REFERENCES dbo.PaymentTransactions(Id),CONSTRAINT FK_MA_Request FOREIGN KEY(SelectedPaymentRequestId) REFERENCES dbo.PaymentRequests(Id),CONSTRAINT FK_MA_Customer FOREIGN KEY(SelectedCustomerId) REFERENCES dbo.Customers(Id),CONSTRAINT CK_MA_Status CHECK(Status IN('RUNNING','UNMATCHED','SUGGESTED','MATCHED','REVIEW','FAILED')));
 CREATE INDEX IX_MA_Transaction ON dbo.MatchingAttempts(PaymentTransactionId,StartedAt DESC);
END
IF OBJECT_ID(N'dbo.MatchingEvidence',N'U') IS NULL CREATE TABLE dbo.MatchingEvidence(Id bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_MatchingEvidence PRIMARY KEY,MatchingAttemptId uniqueidentifier NOT NULL,SignalType varchar(30) NOT NULL,NormalizedValue nvarchar(500) NULL,CandidateType varchar(30) NULL,CandidateId uniqueidentifier NULL,Score decimal(5,2) NULL,Reason nvarchar(500) NULL,CreatedAt datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT FK_ME_Attempt FOREIGN KEY(MatchingAttemptId) REFERENCES dbo.MatchingAttempts(Id),CONSTRAINT CK_ME_Score CHECK(Score IS NULL OR (Score>=0 AND Score<=100)));
IF OBJECT_ID(N'dbo.PaymentReviewActions',N'U') IS NULL BEGIN
 CREATE TABLE dbo.PaymentReviewActions(Id bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_PaymentReviewActions PRIMARY KEY,PartnerId uniqueidentifier NOT NULL,PaymentTransactionId uniqueidentifier NOT NULL,Disposition varchar(30) NOT NULL,TargetType varchar(30) NULL,TargetId uniqueidentifier NULL,OldStatus varchar(20) NULL,NewStatus varchar(20) NULL,ReasonCode varchar(50) NULL,Note nvarchar(1000) NULL,ActorType varchar(20) NOT NULL,ActorId uniqueidentifier NULL,CorrelationId uniqueidentifier NULL,CreatedAt datetime2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT FK_PRA_Partner FOREIGN KEY(PartnerId) REFERENCES dbo.Partners(Id),CONSTRAINT FK_PRA_Transaction FOREIGN KEY(PaymentTransactionId) REFERENCES dbo.PaymentTransactions(Id),CONSTRAINT CK_PRA_Disposition CHECK(Disposition IN('ALLOCATED','CUSTOMER_CREDIT','REFUND_REQUESTED','DUPLICATE','NON_RECEIVABLE','NEEDS_INFORMATION','ESCALATED','IGNORED')),CONSTRAINT CK_PRA_Actor CHECK(ActorType IN('SYSTEM','USER','WORKER','PROVIDER')));
 CREATE INDEX IX_PRA_Transaction ON dbo.PaymentReviewActions(PaymentTransactionId,CreatedAt DESC);
END
GO
IF EXISTS(SELECT 1 FROM sys.check_constraints WHERE parent_object_id=OBJECT_ID('dbo.PaymentMatchingRules') AND name='CK_PMR_AmountNoAuto') ALTER TABLE dbo.PaymentMatchingRules DROP CONSTRAINT CK_PMR_AmountNoAuto;
ALTER TABLE dbo.PaymentMatchingRules ADD CONSTRAINT CK_PMR_AmountNoAuto CHECK(RuleType<>'AMOUNT_ASSIST' OR AutoAllocate=0);
GO
PRINT '033-matching-review-evidence.sql: OK'; GO