/* V1 RC5 050 - fail-closed tenant ownership for financial/legal aggregates. */
USE [TAPortal];
GO
SET XACT_ABORT ON;
SET QUOTED_IDENTIFIER ON;
GO
IF OBJECT_ID(N'dbo.tr_FinancialAccounts_TenantOwnership',N'TR') IS NULL EXEC('CREATE TRIGGER dbo.tr_FinancialAccounts_TenantOwnership ON dbo.FinancialAccounts AFTER INSERT,UPDATE AS BEGIN SET NOCOUNT ON; IF EXISTS(SELECT 1 FROM inserted i JOIN dbo.Companies c ON c.Id=i.CompanyId WHERE i.CompanyId IS NOT NULL AND c.PartnerId<>i.PartnerId) THROW 51810,''FinancialAccount Company belongs to another Partner.'',1; END');
GO
IF OBJECT_ID(N'dbo.tr_PaymentTransactions_TenantOwnership',N'TR') IS NULL EXEC('CREATE TRIGGER dbo.tr_PaymentTransactions_TenantOwnership ON dbo.PaymentTransactions AFTER INSERT,UPDATE AS BEGIN SET NOCOUNT ON; IF EXISTS(SELECT 1 FROM inserted i JOIN dbo.FinancialAccounts a ON a.Id=i.FinancialAccountId WHERE i.FinancialAccountId IS NOT NULL AND a.PartnerId<>i.PartnerId) OR EXISTS(SELECT 1 FROM inserted i JOIN dbo.Companies c ON c.Id=i.CompanyId WHERE i.CompanyId IS NOT NULL AND c.PartnerId<>i.PartnerId) THROW 51811,''PaymentTransaction tenant ownership mismatch.'',1; END');
GO
IF OBJECT_ID(N'dbo.tr_PaymentInstructions_TenantOwnership',N'TR') IS NULL EXEC('CREATE TRIGGER dbo.tr_PaymentInstructions_TenantOwnership ON dbo.PaymentInstructions AFTER INSERT,UPDATE AS BEGIN SET NOCOUNT ON; IF EXISTS(SELECT 1 FROM inserted i JOIN dbo.FinancialAccounts a ON a.Id=i.FinancialAccountId WHERE i.FinancialAccountId IS NOT NULL AND a.PartnerId<>i.PartnerId) OR EXISTS(SELECT 1 FROM inserted i JOIN dbo.PaymentRequests r ON r.Id=i.PaymentRequestId WHERE r.PartnerId<>i.PartnerId) THROW 51812,''PaymentInstruction tenant ownership mismatch.'',1; END');
GO
IF OBJECT_ID(N'dbo.tr_CustomerCashAccounts_TenantOwnership',N'TR') IS NULL EXEC('CREATE TRIGGER dbo.tr_CustomerCashAccounts_TenantOwnership ON dbo.CustomerCashAccounts AFTER INSERT,UPDATE AS BEGIN SET NOCOUNT ON; IF EXISTS(SELECT 1 FROM inserted i JOIN dbo.Customers c ON c.Id=i.CustomerId WHERE c.PartnerId<>i.PartnerId) OR EXISTS(SELECT 1 FROM inserted i JOIN dbo.Companies c ON c.Id=i.CompanyId WHERE i.CompanyId IS NOT NULL AND c.PartnerId<>i.PartnerId) THROW 51813,''CustomerCashAccount tenant ownership mismatch.'',1; END');
GO
IF OBJECT_ID(N'dbo.tr_RefundRequests_TenantOwnership',N'TR') IS NULL EXEC('CREATE TRIGGER dbo.tr_RefundRequests_TenantOwnership ON dbo.RefundRequests AFTER INSERT,UPDATE AS BEGIN SET NOCOUNT ON; IF EXISTS(SELECT 1 FROM inserted i JOIN dbo.Customers c ON c.Id=i.CustomerId WHERE i.CustomerId IS NOT NULL AND c.PartnerId<>i.PartnerId) OR EXISTS(SELECT 1 FROM inserted i JOIN dbo.PaymentTransactions t ON t.Id=i.PaymentTransactionId WHERE i.PaymentTransactionId IS NOT NULL AND t.PartnerId<>i.PartnerId) OR EXISTS(SELECT 1 FROM inserted i JOIN dbo.CustomerCashAccounts a ON a.Id=i.CustomerCashAccountId WHERE i.CustomerCashAccountId IS NOT NULL AND a.PartnerId<>i.PartnerId) OR EXISTS(SELECT 1 FROM inserted i JOIN dbo.Companies c ON c.Id=i.CompanyId WHERE i.CompanyId IS NOT NULL AND c.PartnerId<>i.PartnerId) THROW 51814,''RefundRequest tenant ownership mismatch.'',1; END');
GO
IF OBJECT_ID(N'dbo.tr_MatchingAttempts_TenantOwnership',N'TR') IS NULL EXEC('CREATE TRIGGER dbo.tr_MatchingAttempts_TenantOwnership ON dbo.MatchingAttempts AFTER INSERT,UPDATE AS BEGIN SET NOCOUNT ON; IF EXISTS(SELECT 1 FROM inserted i JOIN dbo.PaymentTransactions t ON t.Id=i.PaymentTransactionId WHERE t.PartnerId<>i.PartnerId) OR EXISTS(SELECT 1 FROM inserted i JOIN dbo.PaymentRequests r ON r.Id=i.SelectedPaymentRequestId WHERE i.SelectedPaymentRequestId IS NOT NULL AND r.PartnerId<>i.PartnerId) OR EXISTS(SELECT 1 FROM inserted i JOIN dbo.Customers c ON c.Id=i.SelectedCustomerId WHERE i.SelectedCustomerId IS NOT NULL AND c.PartnerId<>i.PartnerId) THROW 51815,''MatchingAttempt tenant ownership mismatch.'',1; END');
GO
IF OBJECT_ID(N'dbo.tr_PaymentReviewActions_TenantOwnership',N'TR') IS NULL EXEC('CREATE TRIGGER dbo.tr_PaymentReviewActions_TenantOwnership ON dbo.PaymentReviewActions AFTER INSERT,UPDATE AS BEGIN SET NOCOUNT ON; IF EXISTS(SELECT 1 FROM inserted i JOIN dbo.PaymentTransactions t ON t.Id=i.PaymentTransactionId WHERE t.PartnerId<>i.PartnerId) THROW 51816,''PaymentReviewAction transaction belongs to another Partner.'',1; END');
GO
IF OBJECT_ID(N'dbo.tr_InvoiceRequests_TenantOwnership',N'TR') IS NULL EXEC('CREATE TRIGGER dbo.tr_InvoiceRequests_TenantOwnership ON dbo.InvoiceRequests AFTER INSERT,UPDATE AS BEGIN SET NOCOUNT ON; IF EXISTS(SELECT 1 FROM inserted i JOIN dbo.Customers c ON c.Id=i.CustomerId WHERE i.CustomerId IS NOT NULL AND c.PartnerId<>i.PartnerId) OR EXISTS(SELECT 1 FROM inserted i JOIN dbo.Companies c ON c.Id=i.CompanyId WHERE i.CompanyId IS NOT NULL AND c.PartnerId<>i.PartnerId) THROW 51817,''InvoiceRequest tenant ownership mismatch.'',1; END');
GO
IF OBJECT_ID(N'dbo.tr_SubscriptionCreditGrants_TenantOwnership',N'TR') IS NULL EXEC('CREATE TRIGGER dbo.tr_SubscriptionCreditGrants_TenantOwnership ON dbo.SubscriptionCreditGrants AFTER INSERT,UPDATE AS BEGIN SET NOCOUNT ON; IF EXISTS(SELECT 1 FROM inserted i JOIN dbo.SubscriptionPeriods sp ON sp.Id=i.SubscriptionPeriodId JOIN dbo.PartnerSubscriptions ps ON ps.Id=sp.PartnerSubscriptionId WHERE ps.PartnerId<>i.PartnerId) THROW 51818,''SubscriptionCreditGrant period belongs to another Partner.'',1; END');
GO
PRINT '050-financial-tenant-ownership.sql: OK';
GO